export const nav_bottom = [
  {
    key: 1,
    title: "Categories",
    Link1: "User Interface",
    Link2: "User Experience",
    Link3: "Digital Media",
    Link4: "Programming",
    Link5: "Animation",
    Link6: "Lifestyle",
  },
  {
    key: 2,
    title: "Product",
    Link1: "Pricing",
    Link2: "Overview",
    Link3: "Browse",
    Link4: "Accessibility",
    Link5: "Five",
    Link6: "Changelog",
  },
  {
    key: 3,
    title: "Solutions",
    Link1: "Brainstorming",
    Link2: "Ideation",
    Link3: "Wireframing",
    Link4: "Research",
    Link5: "Design",
    Link6: "Concept",
  },
  {
    key: 4,
    title: "Resources",
    Link1: "Help Center",
    Link2: "Blog",
    Link3: "Tutorials",
    Link4: "FAQs",
    Link5: "Community",
    Link6: "Events",
  },
  {
    key: 5,
    title: " Support",
    Link1: "Contact Us",
    Link2: "Developers",
    Link3: "Documentation",
    Link4: "Integeration",
    Link5: "Reports",
    Link6: "Webinar",
  },
  {
    key: 6,
    title: "Company",
    Link1: "About",
    Link2: "Press",
    Link3: "Events",
    Link4: "Carrers",
    Link5: "Customers",
    Link6: "Partners",
  },
];
